CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "AspNetRoles" (
    "Id" varchar(450) PRIMARY KEY,
    "Name" varchar(256),
    "NormalizedName" varchar(256),
    "ConcurrencyStamp" text
);
CREATE TABLE "AcademicDegrees" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "Title" VARCHAR(150) NOT NULL,
    "Description" TEXT NULL,
    "Version" INTEGER NOT NULL DEFAULT 1,
    "CreatorId" VARCHAR(450) NULL,
    "ModifiedBy" VARCHAR(450) NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ NULL,
    "DeletedAt" TIMESTAMPTZ NULL
);
CREATE TABLE "ApplicationUsers" (
    "Id" VARCHAR(450) PRIMARY KEY,
    "Discriminator" TEXT NOT NULL,
    "UserName" VARCHAR(256),
    "NormalizedUserName" VARCHAR(256),
    "Email" VARCHAR(256),
    "NormalizedEmail" VARCHAR(256),
    "EmailConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
    "PasswordHash" TEXT,
    "SecurityStamp" TEXT,
    "ConcurrencyStamp" TEXT,
    "PhoneNumber" TEXT,
    "PhoneNumberConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
    "TwoFactorEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "LockoutEnd" TIMESTAMPTZ,
    "LockoutEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "AccessFailedCount" INTEGER NOT NULL DEFAULT 0,
    "AcademicDegreeId" UUID NULL,

    CONSTRAINT "FK_ApplicationUsers_AcademicDegrees"
        FOREIGN KEY ("AcademicDegreeId")
        REFERENCES "AcademicDegrees"("Id")
        ON DELETE SET NULL
);
ALTER TABLE "AcademicDegrees"
ADD CONSTRAINT "FK_AcademicDegrees_Creator"
FOREIGN KEY ("CreatorId")
REFERENCES "ApplicationUsers"("Id")
ON DELETE SET NULL;

ALTER TABLE "AcademicDegrees"
ADD CONSTRAINT "FK_AcademicDegrees_ModifiedBy"
FOREIGN KEY ("ModifiedBy")
REFERENCES "ApplicationUsers"("Id")
ON DELETE SET NULL;

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleId" varchar(450) NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles"
        FOREIGN KEY ("RoleId")
        REFERENCES "AspNetRoles"("Id")
        ON DELETE CASCADE
);
CREATE TABLE "ApplicationUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" varchar(450) NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "FK_ApplicationUserClaims_ApplicationUsers"
        FOREIGN KEY ("UserId")
        REFERENCES "ApplicationUsers"("Id")
        ON DELETE CASCADE
);
CREATE TABLE "ApplicationUserLogins" (
    "LoginProvider" varchar(450) NOT NULL,
    "ProviderKey" varchar(450) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" varchar(450) NOT NULL,
    PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_ApplicationUserLogins_ApplicationUsers"
        FOREIGN KEY ("UserId")
        REFERENCES "ApplicationUsers"("Id")
        ON DELETE CASCADE
);
CREATE TABLE "ApplicationUserRoles" (
    "UserId" varchar(450) NOT NULL,
    "RoleId" varchar(450) NOT NULL,
    PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_ApplicationUserRoles_ApplicationUsers"
        FOREIGN KEY ("UserId")
        REFERENCES "ApplicationUsers"("Id")
        ON DELETE CASCADE,
    CONSTRAINT "FK_ApplicationUserRoles_AspNetRoles"
        FOREIGN KEY ("RoleId")
        REFERENCES "AspNetRoles"("Id")
        ON DELETE CASCADE
);
CREATE TABLE "ApplicationUserTokens" (
    "UserId" varchar(450) NOT NULL,
    "LoginProvider" varchar(450) NOT NULL,
    "Name" varchar(450) NOT NULL,
    "Value" text,
    PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_ApplicationUserTokens_ApplicationUsers"
        FOREIGN KEY ("UserId")
        REFERENCES "ApplicationUsers"("Id")
        ON DELETE CASCADE
);
CREATE INDEX "IX_AspNetRoleClaims_RoleId"
ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex"
ON "AspNetRoles" ("NormalizedName")
WHERE "NormalizedName" IS NOT NULL;

CREATE INDEX "IX_ApplicationUserClaims_UserId"
ON "ApplicationUserClaims" ("UserId");

CREATE INDEX "IX_ApplicationUserLogins_UserId"
ON "ApplicationUserLogins" ("UserId");

CREATE INDEX "IX_ApplicationUserRoles_RoleId"
ON "ApplicationUserRoles" ("RoleId");

CREATE INDEX "EmailIndex"
ON "ApplicationUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex"
ON "ApplicationUsers" ("NormalizedUserName")
WHERE "NormalizedUserName" IS NOT NULL;

-- Main Tables

CREATE TABLE "ResearchHours" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "Hours" VARCHAR(150) NOT NULL,
    "Version" INTEGER NOT NULL DEFAULT 1,
    "CreatorId" VARCHAR(450) NULL,
    "ModifiedBy" VARCHAR(450) NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ NULL,
    "DeletedAt" TIMESTAMPTZ NULL ,
    -- 🔗 Foreign Keys
    CONSTRAINT "FK_AcademicDegrees_Creator"
        FOREIGN KEY ("CreatorId")
        REFERENCES "ApplicationUsers"("Id")
        ON DELETE SET NULL,

    CONSTRAINT "FK_AcademicDegrees_ModifiedBy"
        FOREIGN KEY ("ModifiedBy")
        REFERENCES "ApplicationUsers"("Id")
        ON DELETE SET NULL
);


CREATE TABLE "Steps" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "Name" VARCHAR(150) NOT NULL,
    "Version" INTEGER NOT NULL DEFAULT 1,
    "CreatorId" VARCHAR(450) NULL,
    "ModifiedBy" VARCHAR(450) NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ NULL,
    "DeletedAt" TIMESTAMPTZ NULL,

    -- 🔗 Foreign Keys

    CONSTRAINT "FK_Steps_Creator"
        FOREIGN KEY ("CreatorId")
        REFERENCES "ApplicationUsers"("Id")
        ON DELETE SET NULL,

    CONSTRAINT "FK_Steps_ModifiedBy"
        FOREIGN KEY ("ModifiedBy")
        REFERENCES "ApplicationUsers"("Id")
        ON DELETE SET NULL
);
CREATE TABLE "StepRoles" (
    "StepId" UUID NOT NULL, 
    "RoleId" varchar(450) NOT NULL,
    PRIMARY KEY ("StepId", "RoleId"),

    CONSTRAINT "FK_StepRoles_Steps"
        FOREIGN KEY ("StepId")
        REFERENCES "Steps"("Id")
        ON DELETE CASCADE,

    CONSTRAINT "FK_StepRoles_AspNetRoles"
        FOREIGN KEY ("RoleId")
        REFERENCES "AspNetRoles"("Id")
        ON DELETE CASCADE
);

CREATE TABLE "StepDetails" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "NameUserScreen" VARCHAR(150) NOT NULL,
	"NameAdminScreen" VARCHAR(150) NOT NULL,
    "StepId" UUID NOT NULL,
    "Version" INTEGER NOT NULL DEFAULT 1,
    "CreatorId" VARCHAR(450) NULL,
    "ModifiedBy" VARCHAR(450) NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ NULL,
    "DeletedAt" TIMESTAMPTZ NULL,

    -- 🔗 Foreign Keys
    CONSTRAINT "FK_StepDetails_Steps"
        FOREIGN KEY ("StepId")
        REFERENCES "Steps"("Id")
        ON DELETE CASCADE,  -- vì composition

    CONSTRAINT "FK_StepDetails_Creator"
        FOREIGN KEY ("CreatorId")
        REFERENCES "ApplicationUsers"("Id")
        ON DELETE SET NULL,

    CONSTRAINT "FK_StepDetails_ModifiedBy"
        FOREIGN KEY ("ModifiedBy")
        REFERENCES "ApplicationUsers"("Id")
        ON DELETE SET NULL
);

CREATE TABLE "Applications" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "Code" VARCHAR(50) NOT NULL UNIQUE,
    "Title" VARCHAR(200) NOT NULL,
    "Description" TEXT NULL,
    "Status" VARCHAR(50) NOT NULL,
    "StepDetailId" UUID NOT NULL,
    "Version" INTEGER NOT NULL DEFAULT 1,
    "CreatorId" VARCHAR(450) NULL,
    "ModifiedBy" VARCHAR(450) NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ NULL,
    "DeletedAt" TIMESTAMPTZ NULL,
	
    -- 🔗 Foreign Keys
    CONSTRAINT "FK_Applications_StepDetails"
        FOREIGN KEY ("StepDetailId")
        REFERENCES "StepDetails"("Id")
        ON DELETE RESTRICT,

    CONSTRAINT "FK_Applications_ModifiedBy"
        FOREIGN KEY ("ModifiedBy")
        REFERENCES "ApplicationUsers"("Id")
        ON DELETE SET NULL
);

CREATE TABLE "Files" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "Name" VARCHAR(255) NOT NULL,
    "Path" TEXT NOT NULL,
    "Version" INTEGER NOT NULL DEFAULT 1,
    "CreatorId" VARCHAR(450) NULL,
    "ModifiedBy" VARCHAR(450) NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ NULL,
    "DeletedAt" TIMESTAMPTZ NULL,

    -- 🔗 Foreign Keys
    CONSTRAINT "FK_Files_Creator"
        FOREIGN KEY ("CreatorId")
        REFERENCES "ApplicationUsers"("Id")
        ON DELETE SET NULL,

    CONSTRAINT "FK_Files_ModifiedBy"
        FOREIGN KEY ("ModifiedBy")
        REFERENCES "ApplicationUsers"("Id")
        ON DELETE SET NULL
);

CREATE TABLE "ApplicationFiles" (
    "ApplicationId" UUID NOT NULL,
    "FileId" UUID NOT NULL,
    "Version" INTEGER NOT NULL DEFAULT 1,
    "CreatorId" VARCHAR(450) NULL,
    "ModifiedBy" VARCHAR(450) NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ NULL,
    "DeletedAt" TIMESTAMPTZ NULL,

    -- 🔑 Composite Primary Key
    CONSTRAINT "PK_ApplicationFiles"
        PRIMARY KEY ("ApplicationId", "FileId"),

    -- 🔗 Foreign Keys
    CONSTRAINT "FK_ApplicationFiles_Applications"
        FOREIGN KEY ("ApplicationId")
        REFERENCES "Applications"("Id")
        ON DELETE CASCADE,

    CONSTRAINT "FK_ApplicationFiles_Files"
        FOREIGN KEY ("FileId")
        REFERENCES "Files"("Id")
        ON DELETE CASCADE,

    CONSTRAINT "FK_ApplicationFiles_Creator"
        FOREIGN KEY ("CreatorId")
        REFERENCES "ApplicationUsers"("Id")
        ON DELETE SET NULL,

    CONSTRAINT "FK_ApplicationFiles_ModifiedBy"
        FOREIGN KEY ("ModifiedBy")
        REFERENCES "ApplicationUsers"("Id")
        ON DELETE SET NULL
);














